#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use WWW::Mechanize;

sub writeFile{
	my $fileName = $_[0];
	my $fileContent = $_[1];
	open FILE, ">>$fileName";
	print FILE $fileContent;
	close FILE
}

die "Usage: getAllM3u8s <url>" unless length $ARGV[0];

my $url = $ARGV[0];
my @rootURL = $url =~/http.*\//g;
my $root = $rootURL[0];

my $m = WWW::Mechanize->new( agent => "Linux Mozilla", autocheck => 1 );
$m->get($url);
my $masterManifestContent = $m->content;
$m->success or die "Can't access $url.";

&writeFile( "master.m3u8", $masterManifestContent);

my @Variantm3u8s = $masterManifestContent =~ /.*\.m3u8/g;

my $variantURL = $url =~ /(http:.*\/\/.*\/)/;
my $baseVariantURL=$1;


print "baseVariantURL is ".Dumper $baseVariantURL;

foreach my $m3u8URL (@Variantm3u8s){
	my $m3u8 = $baseVariantURL."$m3u8URL";
	
	$m->get($m3u8);
	$m->success or die "Can't access $m3u8.";


	my @dirnames =  split('/',$m3u8 );
	my $directory = $dirnames[-2];
	mkdir $directory, 0777;

	my $filename = $m3u8 =~ /\/([^\/]*)$/;
	&writeFile( './'.$directory.'/'.$1, $m->content);

	my @tsFileNames = $m->content =~ /.*\.ts/g;
	my $url = $m3u8 =~ /(http:.*\/\/.*\/)/;
	my $baseURL = $1;
	
	foreach my $tsFileName (@tsFileNames){
		my $tsURL = $baseURL.$tsFileName;
		print Dumper $tsURL;
		$m->get($tsURL, ':content_file'=>$tsFileName);		
	}

}

#TODO
#download files to named directory
#handle VARIANT manifests with both absolute and relative ts chunk locations